import type { Seat, SeatColumn, SeatDeck, SeatId } from '$types/booking';

/**
 * Seat deck fixtures.
 *
 * This file contains deck geometry and area-level comfort signals only. It
 * holds no passenger data of any kind and must never gain any — occupancy is
 * expressed purely as `available` / `unavailable`.
 */

const ROWS = 11;
const LEFT: SeatColumn[] = ['A', 'B'];
const RIGHT: SeatColumn[] = ['C', 'D'];

/**
 * The twelve selectable seats on the canonical service, matching the
 * "12 seats left" figure on its Explorer card.
 *
 * Availability starts mid-coach, which makes 5C the highest-ranked seat under
 * the default preferences and therefore the illustrative seat carried across
 * seat selection, passenger details, and review.
 */
const AVAILABLE_SEATS: SeatId[] = [
	'1C',
	'2C',
	'3D',
	'5C',
	'5D',
	'6B',
	'7C',
	'8A',
	'8B',
	'9D',
	'10B',
	'11C'
];

/** Step-free seats by the front door. */
const ACCESSIBLE_SEATS: SeatId[] = ['1C', '1D', '2C', '2D'];

/** Rows forming each area-level signal. */
const NEAR_ENTRANCE_ROWS = [1, 2];
const QUIETER_ROWS = [4, 5, 6, 7];

/**
 * Anonymous aggregate area where women passengers are travelling.
 *
 * Applied to a region of the deck, never to a specific person, and filtered to
 * selectable seats only so it can never reveal who occupies a taken seat.
 */
const WOMEN_NEARBY_ROWS = [5, 6, 7, 8];
const WOMEN_NEARBY_COLUMNS: SeatColumn[] = ['A', 'B'];

function buildCanonicalDeck(busId: string): SeatDeck {
	const seats: Seat[] = [];

	for (let row = 1; row <= ROWS; row++) {
		for (const column of [...LEFT, ...RIGHT]) {
			const id = `${row}${column}`;
			const available = AVAILABLE_SEATS.includes(id);

			const womenNearbyArea =
				WOMEN_NEARBY_ROWS.includes(row) && WOMEN_NEARBY_COLUMNS.includes(column);

			seats.push({
				id,
				row,
				column,
				availability: available ? 'available' : 'unavailable',
				signals: {
					window: column === 'A' || column === 'D',
					aisle: column === 'B' || column === 'C',
					accessible: ACCESSIBLE_SEATS.includes(id),
					nearEntrance: NEAR_ENTRANCE_ROWS.includes(row),
					quieter: QUIETER_ROWS.includes(row),
					// Never surfaced on an unavailable seat.
					womenNearby: womenNearbyArea && available
				}
			});
		}
	}

	return {
		busId,
		kind: 'seater',
		layout: '2+2',
		rows: ROWS,
		leftColumns: LEFT,
		rightColumns: RIGHT,
		seats
	};
}

/**
 * The canonical service keeps a hand-written deck.
 *
 * Its availability is deliberate rather than generated: the twelve free seats
 * make 5C the highest-ranked seat under the default preferences, which is what
 * makes 5C the illustrative seat across seat selection, review, and the
 * ticket — and the conductor's boarding plan is built from the same seats, so
 * the two screens agree.
 *
 * Every other service gets a plan generated by `deck.service` from the vehicle
 * working the trip, so the whole timetable can be booked.
 */
export const seatDeckFixtures: Record<string, SeatDeck> = {
	'setc-ultra-deluxe-0830': buildCanonicalDeck('setc-ultra-deluxe-0830')
};
